apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: high-resource-usage
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
    - name: pod-resource-alerts
      rules:
        - alert: HighPodCPUUsage
          expr: |
            sum(rate(container_cpu_usage_seconds_total{namespace="nti-final-project"}[5m])) by (pod)
            / sum(kube_pod_container_resource_limits{namespace="nti-final-project", resource="cpu"}) by (pod)
            > 0.8
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.pod }} CPU usage above 80%"
            description: "Pod {{ $labels.pod }} has exceeded 80% of its CPU limit for more than 5 minutes."

        - alert: HighPodMemoryUsage
          expr: |
            sum(container_memory_working_set_bytes{namespace="nti-final-project"}) by (pod)
            / sum(kube_pod_container_resource_limits{namespace="nti-final-project", resource="memory"}) by (pod)
            > 0.8
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.pod }} memory usage above 80%"
            description: "Pod {{ $labels.pod }} has exceeded 80% of its memory limit for more than 5 minutes."
